# Form implementation generated from reading ui file 'create_password.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 300)
        self.length_input = QtWidgets.QLineEdit(Form)
        self.length_input.setGeometry(QtCore.QRect(270, 30, 141, 20))
        self.length_input.setObjectName("length_input")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.uppercase_check = QtWidgets.QCheckBox(Form)
        self.uppercase_check.setGeometry(QtCore.QRect(40, 111, 97, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uppercase_check.setFont(font)
        self.uppercase_check.setObjectName("uppercase_check")
        self.lowercase_check = QtWidgets.QCheckBox(Form)
        self.lowercase_check.setGeometry(QtCore.QRect(160, 111, 84, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lowercase_check.setFont(font)
        self.lowercase_check.setObjectName("lowercase_check")
        self.digits_check = QtWidgets.QCheckBox(Form)
        self.digits_check.setGeometry(QtCore.QRect(270, 111, 68, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.digits_check.setFont(font)
        self.digits_check.setObjectName("digits_check")
        self.symbols_check = QtWidgets.QCheckBox(Form)
        self.symbols_check.setGeometry(QtCore.QRect(360, 111, 65, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.symbols_check.setFont(font)
        self.symbols_check.setObjectName("symbols_check")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(40, 60, 371, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.prepare_button = QtWidgets.QPushButton(Form)
        self.prepare_button.setGeometry(QtCore.QRect(70, 150, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.prepare_button.setFont(font)
        self.prepare_button.setObjectName("prepare_button")
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setGeometry(QtCore.QRect(80, 210, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("color: rgb(0, 0, 255);")
        self.result_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.copy_button = QtWidgets.QPushButton(Form)
        self.copy_button.setGeometry(QtCore.QRect(200, 270, 71, 17))
        self.copy_button.setObjectName("copy_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Şifrənin uzunluğunu girin:"))
        self.label_2.setText(_translate("Form", "İstifadə olunacaq xarakterlər"))
        self.uppercase_check.setText(_translate("Form", "Böyük Hərf"))
        self.lowercase_check.setText(_translate("Form", "Kiçik hərf"))
        self.digits_check.setText(_translate("Form", "Rəqəm"))
        self.symbols_check.setText(_translate("Form", "Simvol"))
        self.prepare_button.setText(_translate("Form", "Hazırla"))
        self.result_label.setText(_translate("Form", "TextLabel"))
        self.copy_button.setText(_translate("Form", "Kopyala"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
